language: node_js
node_js: 8.1.2
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn test-travis
notifications:
  email:
    on_success: never
    on_failure: never
    on_pull_requests: false
  slack: grapheel:StZjU1wi6TtaZFkYyGaOBc4m
deploy:
  provider: heroku
  api_key:
    secure: KIheBAxH3PuA2XztneV2kjSSO420L4V4oD+yHeyuLx9TopR/LxrouquiSvOVhq7GG2bidc5E1eFQKrCJKMmwyQ4XGAYykoTOWP/Dd2hcKtAzVlJ7HGicuzxP8ne2G98hYjhs0+IMh9LH5OUQfXnpiweimnaOAQI8f+IE4aY25o3o1ISxut+Nmj8DQRkttj/IZRSNbrajUxp0P52UeN2tngXJLu/Zl/Vo9Ojn+wWLE5k0KEOFm/Ybnom3Na2cBhEVU7fmnZPoFrP1x5CqIE0J7lJFnxCuLX1MfY8dpGzoBX0rSMq4AbkjHD6vapOQNvilaGINYTiQacN+/AARuCWGyi4bbqBjQHZQ51/XZFdFqMG7EizQSKE8PzmQF6PpOdDNLm9lGW2p3ASH3PtHCjsA3bj+ayQJcLyIQGkPAcRt7tvSi8JmSgZOvfsYvD0eR0ZM5clEHTqBeRFV0xA+e3/jA6uqhz0xMbjcWfuF13JEStTN6UEYdCkod3WGm9I7Cxm6eoW/TWCNQp+qEVst4sp+Vx5b06pSh2jKN4HbTYos5sacfTxUexQoqQolVpOKY40u43NB173y8oYqd7ybXtHln/4rtfyJ4DMlN6AepM3Xf+0dJwjDZEHGJM4HzzX3CAQkChkXVHXiErsAb1yD6HYOHqcyi32pSIY6U+fjGlLZ7Xs=
  app: grapheel-iris-front-end
