language: node_js
node_js: 8.10.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn test-travis
notifications:
  email:
    on_success: never
    on_failure: never
    on_pull_requests: false
  slack: grapheel:StZjU1wi6TtaZFkYyGaOBc4m
deploy:
  provider: heroku
  api_key:
    secure: bAFYivsQvGlZ8EJPM/Qt0A+Tg3WMca7BxYRCmHthkmUWAUcYCDH3X6Ax3Z3D8e8lNYKDAum8y/TsilVoVn1WlCakWPIJepZZqAX+PS0MrgtjfqCPyjvaJHcdxvziDp7KrsWcqEOAn1ExdFSDIFxE4uXXwONzRMmvEYM/aoX6pRbbO4jQqyOdmq9EuY6Le1ezcHeaT9BOOFBNKtj8BVQ2Ct8rZ6poYvnPFNy2RzHMQvqIw0HN6WHyi+EyhdDWgiYj6lbpd/wTrUMA1h+4zyRjnO3wTkwj8aX73ROcaUgMaX486ieI42SHJSZaMR0IrwlXC8iTiYCzqEy6GWxhKefXlWMh9GPWUy5AVoYJq+m4+6lTnxDW1r6UvArmXpmbaQosVGCyT5PoTqBWFVZ4R8LXuOaH7aVZL7H9tWZHPV7DKoyDXPyvVS5Gaj5tWdIU9dLNMNH3a84zLc6bgsoBptPIqu48HAaFeXe3P9FC2U6u8OBSBLydtTyx0ZlF9OvY63vIeVcBFaYLhxTgd8JFWJ1giV9Es+N/9pp3b4KyfDueHYZimrKoYncA/F+71M2PPth4IJELdC+Kd7sBSkRhVxmsw1L4dwKMJDfSKY8hca4FZQecFyCRSd7HJtCgIc1QmEcHTxm5Y2yU2zQfm+D8D3c0QLr89aF3UW3cYc26bAiI7mU=
  app: grapheel-iris-front-end
